meta:
  target:   glow
  url:      https://concourse.dev.maio.me
  team:     saltbox-formulas

  name:     weave-net-formula
  pipeline: weave-net-formula

  registry:
    repository: containers.dev.maio.me
    auth:
      username: ((glow_registry_ci.username))
      password: ((glow_registry_ci.password))

  formula:
    source:
      uri: https://glow.dev.maio.me/saltbox-formulas/weave-net.git
      branch: master