meta:
  name:     weave-net-formula
  target:   glow
  url:      https://concourse.dev.maio.me
  team:     main
  pipeline: weave-net-formula

  registry:
    repository: containers.dev.maio.me
    auth:
      username: ((glow_registry_ci.username))
      password: ((glow_registry_ci.password))
